---
lint: |
  set -e
  yamllint .
  ansible-lint -v --exclude=.tox
dependency:
  name: galaxy
driver:
  name: docker
verifier:
  name: ansible
provisioner:
  name: ansible
  options:
    v: True
  log: True
platforms:
  - name: keepalived-debian11
    image: debian:bullseye
    dockerfile: Dockerfile.j2
    privileged: true
    override_command: false
    tmpfs:
      - /run
      - /run/lock
      - /tmp
    capabilities:
      - SYS_ADMIN
    security_opts:
      - seccomp=unconfined
